# Generated by Django 3.0.6 on 2020-05-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20200515_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='release_date',
            new_name='receive_date',
        ),
    ]
