# Generated by Django 3.0.6 on 2020-05-17 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0004_auto_20200515_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='isRented',
        ),
        migrations.AlterField(
            model_name='video',
            name='renter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
